### ISSUE TITLE
Use rem instead of mod

### ISSUE THREAD

**Issue by axman6** [vmchale/fast-arithmetic#2]
`rem` is generally faster than `mod` and returns the same results as rem for positive arguments - making this change would make the benchmarking comparison a little more fair.

Also the haskell factorial functions should be tail recursive, again to give a fair comparison.
```haskell
hsFactorial :: Int -> Int
hsFactorial n = product [n,n-1..1]

hsDoubleFactorial :: Int -> Int
hsDoubleFactorial n = product [n,n-2..1]
```

**Comment by vmchale** [comment]
I ripped out several things so the factorial stuff is no longer needed, though that does change things. I still use `mod` in places for the sake of clarity, though I'd be amenable to changing this if Haskell had a way to sanitize inputs (e.g. LiquidHaskell across packages?). At the moment the change doesn't make a dramatic difference (5x slower vs 4x slower).

**Comment by axman6** [comment]
Yeah the obvious choice would be be to use a Natural type instead of Integer/Int.
